#servidor
server:
  host: localhost
  port: 8080

aplicacao:
  versao: 1.1
  nome: ordering system

#Spring
spring:
  application:
    name: diploma-digital
  datasource:
    url: jdbc:mysql://sqlexpress.crkmqi2w23yz.sa-east-1.rds.amazonaws.com:3306/dbtest
    username: admin
    password: PezA2611
    jpa:
      hibernate:
        ddl-auto: update
      properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQLDialect
          show_sql: true
  servlet:
    multipart:
      max-file-size: 80MB
      max-request-size: 80MB

#Feign
feign:
  client:
    config:
      default:
        connectTimeout: 60000
        readTimeout: 60000
  httpclient:
    disable-ssl-validation: false
    enabled: false
  okhttp:
    enabled: true

#autenticacao OAuth2
#security:
#  oauth2:
#    client:
#      scope: password
#      client-id: 607c6765-d6c9-4c20-a4ff-c373a3d50794
#      client-secret: 5eabc608-8003-4105-8ed1-5cc45c7c5eb8

#LOGGING
logging:
  level:
    root: INFO
    com.sample.feign.demofeigncustomconfig: INFO
    br.infuse: INFO
    org.springframework.web.client: INFO
    org.springframework.security.oauth2: INFO
