create
definer = admin@`%` procedure PRC_MSG_RETORNO(IN I_COD int, INOUT O_DESC_CURTO varchar(100))
BEGIN
    DECLARE CONTINUE HANDLER FOR SQLEXCEPTION SET @COD_RETORNO = 1;
    SET @COD_RETORNO := 0;
    SET @DESC_CURTO := 'SUCESSO';

    IF @COD_RETORNO = 0 THEN
SELECT @DESC_CURTO INTO O_DESC_CURTO;
END IF;
END;