DELIMITER ;;

CREATE DEFINER=`admin`@`%` PROCEDURE `PRC_MSG_RETORNO`(
    IN `I_COD` INT,
    INOUT `O_DESC_CURTO` VARCHAR(100)
)
BEGIN
    DECLARE CONTINUE HANDLER FOR SQLEXCEPTION SET @COD_RETORNO=1;
    SET @COD_RETORNO := 0;
    SET @DESC_CURTO := 'SUCESSO';

    IF @COD_RETORNO = 0 THEN
SELECT @DESC_CURTO INTO O_DESC_CURTO;
END IF;
END ;;
DELIMITER ;