DELIMITER ;;

CREATE DEFINER=`admin`@`%` PROCEDURE `PROC_REGISTER_ORDERS`(
    IN `CLIENT` INT,
    IN `CONTROL` INT,
    IN `PRODUCT` VARCHAR(100),
    IN `V_PRODUCT` DECIMAL(10,2),
    IN `AMOUNT` INT,
    IN `REGISTER` DATETIME
)
BEGIN
    DECLARE O_DESC_CURTO VARCHAR(100);
    DECLARE O_COD_RETORNO INT;

    DECLARE V_PERC_DISCOUNT FLOAT;
    DECLARE V_DISCOUNT DECIMAL(10,2);
    DECLARE V_TOTAL DECIMAL(10,2);
    DECLARE V_ORDER DECIMAL(10,2);

    DECLARE CONTINUE HANDLER FOR SQLEXCEPTION
    BEGIN
    GET DIAGNOSTICS CONDITION 1
        O_COD_RETORNO = RETURNED_SQLSTATE, O_DESC_CURTO = MESSAGE_TEXT;
    END;

    SET O_COD_RETORNO := 0;
    SET O_DESC_CURTO := '';

    SET V_TOTAL := V_PRODUCT*AMOUNT;

    IF AMOUNT > 5 AND AMOUNT < 10 THEN
        SET V_PERC_DISCOUNT := 0.05;
    ELSEIF AMOUNT >= 10 THEN
        SET V_PERC_DISCOUNT := 0.10;
    ELSE
        SET V_PERC_DISCOUNT := 0; -- Setting default discount to 0 if not applicable
    END IF;

    SET V_DISCOUNT := V_TOTAL*V_PERC_DISCOUNT;
    SET V_ORDER := V_TOTAL-V_DISCOUNT;

    INSERT INTO tb_orders(
        CLIENT_ID, NUM_CONTROL, NM_PRODUCT, VL_PRODUCT, AMOUNT_ORDER, PERCENT_DISCOUNT, VL_DISCOUNT, VL_ORDER, DT_REGISTER
    ) VALUES (
             CLIENT, CONTROL, PRODUCT, V_PRODUCT, AMOUNT, V_PERC_DISCOUNT, V_DISCOUNT, V_ORDER, REGISTER
    );

CALL PRC_MSG_RETORNO(O_COD_RETORNO, O_DESC_CURTO);

SELECT O_COD_RETORNO, O_DESC_CURTO;

END ;;
DELIMITER ;